apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad2-api
  labels:
    app: backendapi
spec:
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
        - name: api-app
          image: rozdolsky33/squad2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-squad2-api
  name: service-squad2-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: backendapi
